/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as DeskChannelsRouteImport } from './routes/desk/channels'
import { Route as DeskClientsRouteImport } from './routes/desk/clients'
import { Route as DeskInboxRouteImport } from './routes/desk/inbox'
import { Route as DeskKnowledgeRouteImport } from './routes/desk/knowledge'
import { Route as DeskReportsRouteImport } from './routes/desk/reports'
import { Route as DeskTicketsRouteImport } from './routes/desk/tickets'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalKnowledgeRouteImport } from './routes/portal/knowledge'
import { Route as PortalNewRouteImport } from './routes/portal/new'
import { Route as PortalTicketsRouteImport } from './routes/portal/tickets'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksFacebookRouteImport } from './routes/api/webhooks/facebook'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as DeskClientsClientIdRouteImport } from './routes/desk/clients.$clientId'
import { Route as DeskTicketsTicketIdRouteImport } from './routes/desk/tickets.$ticketId'
import { Route as PortalTicketsTicketIdRouteImport } from './routes/portal/tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskChannelsRoute = DeskChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => DeskRoute,
} as any)
const DeskClientsRoute = DeskClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DeskRoute,
} as any)
const DeskInboxRoute = DeskInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DeskRoute,
} as any)
const DeskKnowledgeRoute = DeskKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => DeskRoute,
} as any)
const DeskReportsRoute = DeskReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTicketsRoute = DeskTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DeskRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalKnowledgeRoute = PortalKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNewRoute = PortalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTicketsRoute = PortalTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => PortalRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksFacebookRoute = ApiWebhooksFacebookRouteImport.update({
  id: '/api/webhooks/facebook',
  path: '/api/webhooks/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskClientsClientIdRoute = DeskClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => DeskClientsRoute,
} as any)
const DeskTicketsTicketIdRoute = DeskTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => DeskTicketsRoute,
} as any)
const PortalTicketsTicketIdRoute = PortalTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => PortalTicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/desk/channels': typeof DeskChannelsRoute
  '/desk/clients': typeof DeskClientsRouteWithChildren
  '/desk/inbox': typeof DeskInboxRoute
  '/desk/knowledge': typeof DeskKnowledgeRoute
  '/desk/reports': typeof DeskReportsRoute
  '/desk/tickets': typeof DeskTicketsRouteWithChildren
  '/portal/knowledge': typeof PortalKnowledgeRoute
  '/portal/new': typeof PortalNewRoute
  '/portal/tickets': typeof PortalTicketsRouteWithChildren
  '/desk/': typeof DeskIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/desk/clients/$clientId': typeof DeskClientsClientIdRoute
  '/desk/tickets/$ticketId': typeof DeskTicketsTicketIdRoute
  '/portal/tickets/$ticketId': typeof PortalTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/desk/channels': typeof DeskChannelsRoute
  '/desk/clients': typeof DeskClientsRouteWithChildren
  '/desk/inbox': typeof DeskInboxRoute
  '/desk/knowledge': typeof DeskKnowledgeRoute
  '/desk/reports': typeof DeskReportsRoute
  '/desk/tickets': typeof DeskTicketsRouteWithChildren
  '/portal/knowledge': typeof PortalKnowledgeRoute
  '/portal/new': typeof PortalNewRoute
  '/portal/tickets': typeof PortalTicketsRouteWithChildren
  '/desk': typeof DeskIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/desk/clients/$clientId': typeof DeskClientsClientIdRoute
  '/desk/tickets/$ticketId': typeof DeskTicketsTicketIdRoute
  '/portal/tickets/$ticketId': typeof PortalTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/desk/channels': typeof DeskChannelsRoute
  '/desk/clients': typeof DeskClientsRouteWithChildren
  '/desk/inbox': typeof DeskInboxRoute
  '/desk/knowledge': typeof DeskKnowledgeRoute
  '/desk/reports': typeof DeskReportsRoute
  '/desk/tickets': typeof DeskTicketsRouteWithChildren
  '/portal/knowledge': typeof PortalKnowledgeRoute
  '/portal/new': typeof PortalNewRoute
  '/portal/tickets': typeof PortalTicketsRouteWithChildren
  '/desk/': typeof DeskIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/desk/clients/$clientId': typeof DeskClientsClientIdRoute
  '/desk/tickets/$ticketId': typeof DeskTicketsTicketIdRoute
  '/portal/tickets/$ticketId': typeof PortalTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/login'
    | '/portal'
    | '/desk/channels'
    | '/desk/clients'
    | '/desk/inbox'
    | '/desk/knowledge'
    | '/desk/reports'
    | '/desk/tickets'
    | '/portal/knowledge'
    | '/portal/new'
    | '/portal/tickets'
    | '/desk/'
    | '/portal/'
    | '/api/auth/$'
    | '/api/webhooks/facebook'
    | '/api/webhooks/whatsapp'
    | '/desk/clients/$clientId'
    | '/desk/tickets/$ticketId'
    | '/portal/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/desk/channels'
    | '/desk/clients'
    | '/desk/inbox'
    | '/desk/knowledge'
    | '/desk/reports'
    | '/desk/tickets'
    | '/portal/knowledge'
    | '/portal/new'
    | '/portal/tickets'
    | '/desk'
    | '/portal'
    | '/api/auth/$'
    | '/api/webhooks/facebook'
    | '/api/webhooks/whatsapp'
    | '/desk/clients/$clientId'
    | '/desk/tickets/$ticketId'
    | '/portal/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/login'
    | '/portal'
    | '/desk/channels'
    | '/desk/clients'
    | '/desk/inbox'
    | '/desk/knowledge'
    | '/desk/reports'
    | '/desk/tickets'
    | '/portal/knowledge'
    | '/portal/new'
    | '/portal/tickets'
    | '/desk/'
    | '/portal/'
    | '/api/auth/$'
    | '/api/webhooks/facebook'
    | '/api/webhooks/whatsapp'
    | '/desk/clients/$clientId'
    | '/desk/tickets/$ticketId'
    | '/portal/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksFacebookRoute: typeof ApiWebhooksFacebookRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/channels': {
      id: '/desk/channels'
      path: '/channels'
      fullPath: '/desk/channels'
      preLoaderRoute: typeof DeskChannelsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/clients': {
      id: '/desk/clients'
      path: '/clients'
      fullPath: '/desk/clients'
      preLoaderRoute: typeof DeskClientsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/inbox': {
      id: '/desk/inbox'
      path: '/inbox'
      fullPath: '/desk/inbox'
      preLoaderRoute: typeof DeskInboxRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/knowledge': {
      id: '/desk/knowledge'
      path: '/knowledge'
      fullPath: '/desk/knowledge'
      preLoaderRoute: typeof DeskKnowledgeRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/reports': {
      id: '/desk/reports'
      path: '/reports'
      fullPath: '/desk/reports'
      preLoaderRoute: typeof DeskReportsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/tickets': {
      id: '/desk/tickets'
      path: '/tickets'
      fullPath: '/desk/tickets'
      preLoaderRoute: typeof DeskTicketsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/knowledge': {
      id: '/portal/knowledge'
      path: '/knowledge'
      fullPath: '/portal/knowledge'
      preLoaderRoute: typeof PortalKnowledgeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/new': {
      id: '/portal/new'
      path: '/new'
      fullPath: '/portal/new'
      preLoaderRoute: typeof PortalNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tickets': {
      id: '/portal/tickets'
      path: '/tickets'
      fullPath: '/portal/tickets'
      preLoaderRoute: typeof PortalTicketsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/facebook': {
      id: '/api/webhooks/facebook'
      path: '/api/webhooks/facebook'
      fullPath: '/api/webhooks/facebook'
      preLoaderRoute: typeof ApiWebhooksFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/clients/$clientId': {
      id: '/desk/clients/$clientId'
      path: '/$clientId'
      fullPath: '/desk/clients/$clientId'
      preLoaderRoute: typeof DeskClientsClientIdRouteImport
      parentRoute: typeof DeskClientsRoute
    }
    '/desk/tickets/$ticketId': {
      id: '/desk/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/desk/tickets/$ticketId'
      preLoaderRoute: typeof DeskTicketsTicketIdRouteImport
      parentRoute: typeof DeskTicketsRoute
    }
    '/portal/tickets/$ticketId': {
      id: '/portal/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/portal/tickets/$ticketId'
      preLoaderRoute: typeof PortalTicketsTicketIdRouteImport
      parentRoute: typeof PortalTicketsRoute
    }
  }
}

interface DeskClientsRouteChildren {
  DeskClientsClientIdRoute: typeof DeskClientsClientIdRoute
}

const DeskClientsRouteChildren: DeskClientsRouteChildren = {
  DeskClientsClientIdRoute: DeskClientsClientIdRoute,
}

const DeskClientsRouteWithChildren = DeskClientsRoute._addFileChildren(
  DeskClientsRouteChildren,
)

interface DeskTicketsRouteChildren {
  DeskTicketsTicketIdRoute: typeof DeskTicketsTicketIdRoute
}

const DeskTicketsRouteChildren: DeskTicketsRouteChildren = {
  DeskTicketsTicketIdRoute: DeskTicketsTicketIdRoute,
}

const DeskTicketsRouteWithChildren = DeskTicketsRoute._addFileChildren(
  DeskTicketsRouteChildren,
)

interface DeskRouteChildren {
  DeskChannelsRoute: typeof DeskChannelsRoute
  DeskClientsRoute: typeof DeskClientsRouteWithChildren
  DeskInboxRoute: typeof DeskInboxRoute
  DeskKnowledgeRoute: typeof DeskKnowledgeRoute
  DeskReportsRoute: typeof DeskReportsRoute
  DeskTicketsRoute: typeof DeskTicketsRouteWithChildren
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskChannelsRoute: DeskChannelsRoute,
  DeskClientsRoute: DeskClientsRouteWithChildren,
  DeskInboxRoute: DeskInboxRoute,
  DeskKnowledgeRoute: DeskKnowledgeRoute,
  DeskReportsRoute: DeskReportsRoute,
  DeskTicketsRoute: DeskTicketsRouteWithChildren,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface PortalTicketsRouteChildren {
  PortalTicketsTicketIdRoute: typeof PortalTicketsTicketIdRoute
}

const PortalTicketsRouteChildren: PortalTicketsRouteChildren = {
  PortalTicketsTicketIdRoute: PortalTicketsTicketIdRoute,
}

const PortalTicketsRouteWithChildren = PortalTicketsRoute._addFileChildren(
  PortalTicketsRouteChildren,
)

interface PortalRouteChildren {
  PortalKnowledgeRoute: typeof PortalKnowledgeRoute
  PortalNewRoute: typeof PortalNewRoute
  PortalTicketsRoute: typeof PortalTicketsRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalKnowledgeRoute: PortalKnowledgeRoute,
  PortalNewRoute: PortalNewRoute,
  PortalTicketsRoute: PortalTicketsRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksFacebookRoute: ApiWebhooksFacebookRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
